//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spotzer.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpotzerEntities : DbContext
    {
        public SpotzerEntities()
            : base("name=SpotzerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_adwordcampaign> tbl_adwordcampaign { get; set; }
        public DbSet<tbl_lineitem> tbl_lineitem { get; set; }
        public DbSet<tbl_order> tbl_order { get; set; }
        public DbSet<tbl_websitedetails> tbl_websitedetails { get; set; }
    }
}
